#!/bin/bash

set -ex

checker_build="/tmp/checker.$(basename "$0")"
source common
checker_image

is_released() {
  local image_tag="sealos-$ARCH"
  pushd "$(mktemp -d)" >/dev/null || exit
  until git ls-remote --refs --sort="-version:refname" --tags "https://github.com/labring/sealos.git" | cut -d/ -f3- | grep -E "^v[5-9].+"; do sleep 3; done >.versions

  while read -r vSEALOS; do
    if [[ "$vSEALOS" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && curl -sL "https://github.com/labring/sealos/releases/tag/$vSEALOS" | grep '="repo_releases"' >/dev/null; then
      echo "$vSEALOS"
    elif [[ "$vSEALOS" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[Rr][Cc][0-9]*$ ]] || [[ "$vSEALOS" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[Rr][Cc]\.[0-9]+$ ]]; then
      echo "$vSEALOS"
    fi
  done <.versions | sort
  popd >/dev/null
}

if [[ -n "${SEALOS_VERSION:-}" ]]; then
  SEALOS_VERSIONS="v${SEALOS_VERSION#v}"
else
  SEALOS_VERSIONS="$(is_released)"
fi

for vSEALOS in $SEALOS_VERSIONS; do
  image_tag="sealos-$vSEALOS-$ARCH"
  pushd "$(mktemp -d)" >/dev/null || exit
  until curl -sL "https://github.com/labring/sealos/releases/download/$vSEALOS/sealos_${vSEALOS#*v}_linux_$ARCH.tar.gz" | tar -xz; do sleep 3; done
  find . -type f -exec file {} \; | grep -E "(executable,|/ld-)" | awk -F: '{print $1}' | grep -vE "\.so" | while IFS='' read -r elf; do sudo chmod a+x "$elf" && binary_verify "$elf"; done
  cat <<EOF >"/tmp/$image_tag"
FROM alpine:3
ADD . /sealos
EOF
  tree -L 5
  docker buildx build \
    --platform "linux/$ARCH" \
    --no-cache \
    --push \
    --label "org.opencontainers.image.source=https://github.com/$REPOSITORY" \
    --label "org.opencontainers.image.description=sealos-$vSEALOS container image" \
    --label "org.opencontainers.image.licenses=MIT" \
    -t "$REGISTRY/$REPOSITORY:$image_tag" \
    -f "/tmp/$image_tag" \
    .
  popd >/dev/null
done

rm -rf /tmp/tmp.*
